### ISSUE TITLE
Questions: Why not use Tasks? Would a single send thread be more optimal?

### ISSUE THREAD

**Issue by snarlynarwhal** [vis2k/Telepathy#57]
Hello, I've just been reading through the source code to learn about socket programming and had a couple of questions. FYI I have a basic understanding of sockets and threads so please bare with me if the answers to these are obvious. :)

- How come this project uses threads over tasks?
- Why does each connection have it's own send thread instead of having a single send thread?
- If the app has 1000 clients/threads, won't the overhead of changing the thread context make for worse performance?

**Comment by paulpach** [comment]
1)  when you say task, I assume asynchronous programming?   We have tested async/await,  BeginRead/EndRead and SocketAsyncEventArgs.   There seems to be something seriously broken in unity's socket implementation because none of them scale well.   Check out the 2018 branch,  it has a very simple async/await based tcp transports that does not use threads.

2) because sending messages is currently synchronous,  so you want to send 10 messages to 10 different connections,  and one of them happens to be very slow,  you are affecting latency on all of them.   The alternative is to send asynchronous,  and it is fully implemented in 2018 branch,  but again,  performed poorly in our tests.

3) yes,  context switching is expensive.  but it turns out that tasks in unity are even more expensive.  The async based transports uses _more_ cpu in our tests.

Note that if we use the async/await transport outside of unity,  it easily outperforms threads.  The problem is running it under unity.

**Comment by snarlynarwhal** [comment]
Thanks for the info, very much appreciated! If I use a .NET Core console app as a game server instead of a headless Unity instance, I should use async/await instead of threads, correct? Maybe Telepathy could introduce a layer of abstraction where the developer can configure whether to use threads or tasks. I do not see a 2018 branch, but do see 3 async branches: `async`, `async-await`, and `async-await-unity`. I assume you mean the last one?

**Comment by paulpach** [comment]
sorry for the misinformation,  here is the code for the async tcp code:
https://github.com/vis2k/Mirror/tree/2018/Assets/Mirror/Runtime/Transport/Tcp

Yes,  if you have a .net core console app,  definitely use async/await.  It performs and scales much better.

**Comment by snarlynarwhal** [comment]
Thanks so much @paulpach!
