### ISSUE TITLE
What platforms does Telepathy support?

### ISSUE THREAD

**Issue by zhuyidiwow** [vis2k/Telepathy#58]
Hi developers! I was looking for a good networking library to use with Unity as Unity is in this weird transitioning period from UNet to their new transport layer. Telepathy looks pretty promising! I do want to make my game cross-platform, so I'm wondering what platforms do you support/have tested on. Thanks!

**Comment by paulpach** [comment]
Telepathy supports ios, android, mac, windows, linux and consoles.   

The biggest issue you might face is webgl.  There is another transport for webgl based on websocket.  

If you are making a game, take a look at mirror,  it uses telepathy for the above platforms, it has a websocket transport for webgl.  It is high level and helps you focus on your game logic instead of networking.

**Comment by zhuyidiwow** [comment]
Thanks! I will give mirror a try.
