### ISSUE TITLE
msg.connectionId

### ISSUE THREAD

**Issue by dupperT** [vis2k/Telepathy#73]
Why does the msg.connectionId always increase even when someone disconnects? 

e.g

Server starts.

Client1 connects  // msg.connectionId = 1
client1 disconnects 

client1 reconnects // msg.connectionId = 2

why doesn't the disconnect takes away the connection id?

**Comment by paulpach** [comment]
all we need connectionId to do is be unique.  That is all.  It is used to tell who sent a message and who to reply to,  so all it needs to do is identify the **session**.   Every new connection (or reconnect)  is a new session so it gets a new session id. 

I am guessing you are asking because you want some way to identify the user? 
If that is the case,  what you really want is authentication (even if it is is not secure).  We are adding one to Mirror in https://github.com/vis2k/Mirror/pull/1057,   but authentication is out of scope for Telepathy.
